export class Jogos {
    constructor(title, releseData, imagesLink, publisher, genero, description, progress) {
        this.title = title;
        this.releseData = releseData;
        this.imagesLink = imagesLink;
        this.publisher = publisher;
        this.genero = genero;
        this.description = description;
        this.progress = progress;
    }
}

export const jogosData = [
    new Jogos(
        "Starfield",
        "00/00/0000",
        "starfield",
        "Microsoft",
        "RPG | Aventura",
        "Jogo com mais de mil planetas exploraveis",
        80,
    ),
    new Jogos(
        "Redfall",
        "00/00/0000",
        "redfall",
        "Microsoft",
        "",
        "",
        38,
    ),
    new Jogos(
        "Star Wars Jedi Survivor",
        "00/00/0000",
        "star-wars-jedi-survivor",
        "Steam | Microsoft | PSN",
        "Aventura | Ação",
        "Joguinho de star wars bugado",
        57,
    ),
    new Jogos(
        "Spider Man 02",
        "00/00/0000",
        "spider-man-2",
        "PSN",
        "",
        "",
        78,
    ),
    new Jogos(
        "Baldur's Gate III",
        "00/00/0000",
        "baldurs-gate-III",
        "Steam | PSN",
        "",
        "",
        38,
    ),
    new Jogos(
        "Dead Space",
        "00/00/0000",
        "dead-space-remake",
        "",
        "",
        "",
        38,
    ),
    new Jogos(
        "Diablo IV",
        "00/00/0000",
        "diablo-IV",
        "",
        "",
        "",
        38,
    ),
    new Jogos(
        "Final Fantasy XVI",
        "00/00/0000",
        "final-fantasy-XVI",
        "",
        "",
        "",
        38,
    ),
    new Jogos(
        "Fortnite",
        "00/00/0000",
        "fortnite",
        "",
        "",
        "",
        38,
    ),
    new Jogos(
        "Minecraft",
        "00/00/0000",
        "minecraft",
        "",
        "",
        "",
        100,
    ),
    new Jogos(
        "Resident Evil 4",
        "00/00/0000",
        "resident-evil-4-re",
        "",
        "",
        "",
        97,
    ),
    new Jogos(
        "Street Fighter 6",
        "00/00/0000",
        "street-fighter-6",
        "",
        "",
        "",
        48,
    ),
    new Jogos(
        "Super Mario 64",
        "00/00/0000",
        "super-mario-64",
        "",
        "",
        "",
        99,
    ),
    new Jogos(
        "Super Mario Bros Wonder",
        "00/00/0000",
        "super-mario-bros-wonder",
        "",
        "",
        "",
        95,
    ),
    new Jogos(
        "The Legend of Zelda Ocarina of Time",
        "00/00/0000",
        "the-legend-of-zelda-ocarina-of-time",
        "",
        "",
        "",
        100,
    ),
    new Jogos(
        "The Legend of Zelda Tears of the Kingdom",
        "00/00/0000",
        "zelda-tears-of-the-kingdom",
        "Nintendo",
        "Aventura",
        "Ùm dos melhores jogos de todos os tempos",
        96,
    ),
];